version: '3'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    ports: 
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - "start-dev"
    volumes:
      - ./keycloak_data:/opt/keycloak/data/

 